### ISSUE TITLE
can a theme-css be aggregated into a minified css?

### ISSUE THREAD

**Issue by lomotelsch** [WebCabin/wcDocker#102]
Hi Jeff,

as I read in your tutorial, a theme-path is needed when instantiating wcDocker to load the theme:

> Notice the themePath, if your theme CSS files are not in the default 'Themes' folder, you will need to
> tell docker about the new path or it will not be able to initialize the default theme.

Can the theme also be included in an aggregated stylesheet anyhow?

Thanks

**Comment by Lochemage** [comment]
@lomotelsch 

I'm not familiar with the term aggregated stylesheet, so I can't really confirm or deny whether that would work.  Would you mind learning me?

**Comment by AFamularo-lomoSoft** [comment]
Hello Jeff,

What my colleagues mentioned is the bundling of separate css files into one css file (min.).

We have several css file for our SPA application. For the deployment we want to bundle this separated files into one minimized file.

Best,
Alexander

**Comment by Lochemage** [comment]
@AFamularo-lomoSoft 

The only thing that the theme system does is create a link element on your page which points to the CSS file for that theme. It is more for convenience, giving you an easy method of dynamically changing your theme on the fly, without hard coding it into your page.

You are more than welcome to embed the theme you want to use into a larger master sheet and simply including that into your header instead.

However, you might want to introduce a small hack if you do not want wcDocker to output an error message in your log when trying to load an invalid theme file.

```
var myDocker = new wcDocker('.dockerContainer', {
    allowDrawers: true,
    theme: undefined
});
```

If the theme option is any string, even an empty one, it will think you are attempting to load a theme of that name. By setting it to undefined, you are effectively making the system think you are simply asking for the theme, rather than assigning one.

**Comment by lomotelsch** [comment]
perfect, thank you
