### ISSUE TITLE
preserve DOM when resizing

### ISSUE THREAD

**Issue by gbaumgart** [WebCabin/wcDocker#106]
I think we had this quite a while ago but I can't find it back. However, here again the problem:

Changing DOM whilst panel/docker resize has tremendous performance impacts, it's so bad that I consider now to drop wcDocker from my code base. I am now desperately looking to hack wcDocker to prevent this from happening at any cost.  

Do you know by chance where to start looking for? I already removed the global 'responsive' resize loop...

**Comment by gbaumgart** [comment]
or is isn't there a way a lightweight variant of resize?

**Comment by Lochemage** [comment]
@gbaumgart 

I may know why this is happening, I would look at the `wcFrame.__updateTabs()` method, the first thing it does is empty the tab widget. This method is called any time the view is resized and the panel needs to re-draw the tab controls. It's been a while since I've looked into it, but I am pretty sure if it were refactored so the panel itself is never removed or changed during this event, it might fix your problem.

I'll try to find some time tonight to look into this, but I can't promise anything.

**Comment by gbaumgart** [comment]
@Lochemage thanks, yeah, i just need a pointer to go from.

**Comment by Lochemage** [comment]
@gbaumgart 

For sure a major performance hit is the tab rebuild system, I think at the time it was just easier to start from scratch and build the tabs every time.  Worst case, if the tab refactoring proves too difficult, the engine could be changed so the resizing is not so responsive (resizing simply shows a ghost divider moving but not actually changing the window until you release).

**Comment by gbaumgart** [comment]
if you like, you can check our application [here](http://www.net-commander.com). You can debug rendering with F12. If you open a console or driver (sub dockers) you can actually see what happens to the FPS when you move a panels around, or just add one.

**Comment by gbaumgart** [comment]
do you have an estimate for 3.0.0 ? I cant really wait much longer. There are also other bugs related to this: when using multiple dockers (another docker in a Panel) and switching between the panels, the splitter positions of the sub docker go bad after resize. 

I can't count the days anymore which I spent for getting docker resizing correctly with sub dockers and I am really tired of it. I do actually have a very well working and precise resizing for my widget system. Just when it comes to wcDocker I am fully screwed. I probably tried all possible combinations of intercepting and forwarding docker events, but no, it always ends up in another mess. I wish you would actually run some tests with nested dockers on your own so that you see what problems popup (really not little problems). I know you think its not needed because you think that only one instance is needed but I can tell you, one instance is might be ok for pretty simple use cases. 

anyway, don't bother. i starting writing a docker system myself now too.

**Comment by WolfieWerewolf** [comment]
@gbaumgart What you are experiencing is not uncommon in the Open Source world.  You start out with an OS project because it speeds up your development; you build on the work that other's have done.  Sometimes you're particular use case goes beyond the spec of the original project.  You have a number of choices.  Fix the bugs / enhance functionality and submit a PR or keep them to yourself, fork the project if you can't align your views with the original author, start a new project and keep it to yourself or open source it.  All of which are perfectly acceptable and viable.  But criticism of a project that you started out enjoying the benefit of is hardly productive.  Just my opinion.

**Comment by gbaumgart** [comment]
@WolfieWerewolf : wasn't criticizing, just pointing out that scalability or nesting isn't possible as it is now with wcDocker and you end up with unmaintainable code to fix that issues. I already tried to get some things into wcDocker but the author rejects already things like separating the html from the code or the whole idea of being able of scaling wcDocker for nested dockers.....

Btw, I did my part to get wcDocker working in larger environments.

**Comment by WolfieWerewolf** [comment]
@gbaumgart Fair comment... I can appreciate where you are coming from, it just felt a little strong that's all.  And I'm sorry for sticking my nose in...I just see a lot of "entitlement" in the Open Source community; a lot of developers seem to think that project maintainers owe them something...I depend on a lot of open source and I"m thankful for it.  I haven't started a project of my own yet but I do try to contribute back to the ones I use in terms of fixes / testing and documentation (which is typically slow to catch up with development).  In your case, and thank you for clarifying, you did try... so if I were in your position I'd fork the project, give it a name to reflect the scalability that you are seeking to address, and seek contributions from others who might share your vision.  wcDockerNested for example... I've only just started using wcDocker and so I haven't found any of it's limitations yet... I wish you luck and hope that you decide to open source it so we can all benefit from your insight and experience.

**Comment by Lochemage** [comment]
@WolfieWerewolf 
I appreciate the feedback. I did feel his comment was a little strong, but it's okay.

@gbaumgart 
I know I've shown resistance to certain changes/fixes, but I don't recall expressly rejecting them. Ultimately, it comes down to free time. I've been able to do spot fixes and quick changes, but when it comes to longer work, it's hard to find time. I know this project is my responsibility, so I try my best and respond to requests and feedback as soon as possible, but I understand that might not be enough.

I know you've made contributions, and we've discussed many features together. One of the reasons for making this project open source and giving it to the public were for these things. If your plan is to start your own project to address these issues, then I would ask that you make those fixes here instead. I'd be more than happy to help you however I can with your pull requests. However, if you really must go, know that I sincerely wish you the best, and will miss your company.

**Comment by gbaumgart** [comment]
Ok, wasn't really meant to be harsh. However, I can actually only make sense out if:

1. we move the most hard-coded markup out of the init functions. This one stopped me actually making PRs. The html must go only into a member variable, something i can replace from outside.

2. Then how about: I complete a few more unit tests (automated), for exactly testing nested dockers, in a way that you have it easy to get a fix (to hard for me to fiddle the dom operations). That would be the base for us to make further optimizations or refinements. 

After that, I can have a whole bunch of PRs.  I really love wcDocker and i'd like to get just the last things done. There is not really much to do left. 

g

**Comment by WolfieWerewolf** [comment]
This is awesome guys!  I'm really glad to see you guys working together.  I'm hopeful that as things progress for me with my implementation of wcDocker I'll be able to contribute as well.  Kind Regards.

**Comment by gbaumgart** [comment]
well, there is actually a bigger task left to do I could only little grasp on it: 'quick layouts' something similar of what know from Adobe as 'perspectives'. Basically a simple format (for devs/users) to save and restore layouts (the built-in is too low-level and not really practical). [See here](https://cloud.githubusercontent.com/assets/1205100/15095089/510b2b3c-14b8-11e6-8268-ad0d4fa5c8b6.png); so the user can store layouts into existing predefined layouts, or restore them. A topic for later but this is all what i see left as major task, after dom speed ups.

**Comment by Lochemage** [comment]
@gbaumgart 

I'm afraid I'm a little confused. wcDocker supports being able to save / restore layouts. Your project can leverage this ability and provide multiple 'presets' or 'perspectives' for the user to switch between, all saved layouts are stored as a json string. I am getting the wrong idea?

**Comment by gbaumgart** [comment]
never mind

**Comment by TimNZ** [comment]
Is this discussion still valid - I have a few tabs and responsiveness in resizing a window and panels seems fine.  Or did I mis-understand the issue?

**Comment by gbaumgart** [comment]
@TimNZ unfortunately, yes. i tried a few things but no. jeff seems the only one to fix this for real.

**Comment by TimNZ** [comment]
You posted a link to http://net-commander.com that now redirects somewhere so I can't play with the example app and see the issues.

You're talking about doing DOM operations doing resize which is a performance consideration regardless of using wcDocker or not.

I've been incorporating code from forks and making my own changes and have plans for more changes, so if you can make it clear what the problem is I can see if it's something I need to look at.  

I resize the reasonably complex demo wcDocker page and it resizes fine for me, good enough for real-world.

**Comment by gbaumgart** [comment]
@TimNZ the problem is that the panel's content is entirely detached during resize, making it hard to debug anything. Do a "inspect element" of some panel's content, then resize. then you'll see that the element focused in dev-tools is gone. apart from performance issues, it also causes flickering whilst resizing. that of course happens only if you have heavy content like [this](https://github.com/net-commander/windows-dist/issues/57).

**Comment by TimNZ** [comment]
Got it now.  

Frankly I'm not too concerned with resize performance as it is an in-frequent action by users.
Perhaps adding an option to turn off real-time resizing is ok?

I'm also using Electron and cloned iframe.js (wcIFrame) to make a webview (wcWebView) class.  
Since moving iframe/webview around DOM causes them to refresh, wcDocker handles that by just changing the absolute position of these specially to avoid a refresh by leaving in the same place in the DOM.

I don't think there's any reason why that couldn't be extended to your other content?
Really it should just be the default mechanism for all panel content.

**Comment by gbaumgart** [comment]
well, ok. i am still looking for a way to preserve the dom during resize, despite the why. i personally would never ever detach anything from the dom in this case. in top, resizing a panel also causes heavy reflow operations, on the whole screen, not just the panels of interest. If you grab an older or low-spec computer and profile your app, you will see how awful this can get (on some you will hear even cooler running up to max.). its so bad, that i am indeed considering to throw wcDocker out again.
