### ISSUE TITLE
Collapse / Expand panel API

### ISSUE THREAD

**Issue by genachka** [WebCabin/wcDocker#25]
Thanks for this very nice jQuery based docking layout! Looks very nice and pretty powerful.

I'd like to add a Collapse / Expand panel button and I don't see an API to allow sizing the panel at runtime (using a basic sample below of what I'm doing).

Also, it would seem that the addButton method requires two more options if isTogglable is true to allow the toggable text to be potentially reverse in addition to the icon: toggableText and toggableTip

```
myPanel.addButton('Collapse', 'fa fa-arrow-left', '<', 'Collapse Files Panel', true, 'fa fa-arrow-right');
    myPanel.on(wcDocker.EVENT_BUTTON, function(data) {
        //note sure how to get the current size and change it accordingly?
    });
```

**Comment by Lochemage** [comment]
Genachka,

Good to hear wcDocker is getting some more use!

The problem is that changing the size of a panel will also change the size
of many other panels that are docked near it as well, so it gets a little
complicated.  However, adding the ability to size the window any time is
one of the things on my TODO list.  I have just not have any priority to
fix that so it's been on the back-burner.

I can't be sure when I will have time to look into it, though, since my day
job has gotten a bit more demanding.  But I will try!


- Lochemage

**Comment by genachka** [comment]
I think wcDocker is a hidden gem and I hope it gets more attention. I've searched for something like it for a long time. There are a few others out there but sadly they appear to be either abandoned or not as far along or commercial. I'm going after a Visual Studio IDE and DockManager (http://www.dockspawn.com/demos/ide/dock_spawn_demo_ide.html) looks exactly like what I want but it's written in Dart and hasn't received much love in a long time. I really like the dock hints it shows when you try to dock something.

For sizing, the panel, you're already doing the update to the other panels when you manually move the splitter, so wouldn't it be the same code just being exposed via API?

Another feature request for the TODO would be to allow tab to be on the bottom (and bonus left, right) on specific panels. :)

Also, I updated the CSS to be closer to the look of DockManager, might be good to offer alternative themes. Let me know if you'd like me to send it to you (and best way to get it to you).

**Comment by Lochemage** [comment]
That is true, sizing is somewhat already implemented, there are just a few
complications when it comes to sizing a panel rather than sizing a splitter
panel.  This is why it is on my TODO list rather than something I don't
plan to do at all.  It shouldn't be too hard to implement, I just need to
find the time to dig into it is all.

As for tabs on the bottom and sides, I can absolutely see that feature
being useful.  I'd have to look into it before I promise anything, though.

If you've made your own custom theme that you think others would like, I
would encourage you to send them my way so I can upload them into wcDockers
theme folder so others can also use it!

Thanks,


- Lochemage

**Comment by Lochemage** [comment]
My latest update now includes the ability to collapse panels to a side, or the bottom. Collapsed panels act as slide-out drawers until they are re-attached back into the main layout.

**Comment by genachka** [comment]
Your 3.0.0 release is shaping up very nicely! I see you also have added the ability to dock panes and control placement of tabs to not only top but now also left, right, and bottom! Thanks for the continued effort to improve windowing library!
