### ISSUE TITLE
Default theme should be separated from wcDocker.css

### ISSUE THREAD

**Issue by dpage** [WebCabin/wcDocker#27]
Hi

Currently the default theme is in wcDocker.css. Whilst this is convenient if the user only wants to use that theme, it makes it harder to create custom themes as they may need to reset or worse clear some of the default styles. For example, in my theme I wish to use the platform/browser standard scrollbars and not the custom ones set in wcDocker.css.

Can this change be made please?

Thanks.

**Comment by Lochemage** [comment]
Dave,

I've considered doing this, but I wasn't sure.  If I did take the theme
out, it would force other users to have to include two css files instead of
one.

However, if you take a look at the source code, style.css file, I have
already broken the code up into two sections.  Around line 360 you should
see a large empty area separating the two parts.  Everything above the line
is considered necessary for wcDocker, while everything below is part of the
default theme.

I've gone ahead and split that file into two, one is in the main folder
(same as wcDocker.css) and is called wcDockerSkeleton.css.  The other is
the default theme, placed in Themes/default.css which you will probably
substitute for your own.

I'm sure it requires some testing, however, something I don't really have
time for right now.  Please let me know how this works out for you!

Thanks,


- Lochemage

**Comment by dpage** [comment]
Thanks Lochemage. If you could add a minimised version of wcDockerSkeleton.css, that would be very helpful as well.

Thank you for the prompt support with my issues!

**Comment by Lochemage** [comment]
My mistake, I forgot to add that to the build process.  It should be there
now!

- Lochemage

**Comment by Lochemage** [comment]
Dave,

Just a follow up, did the skeleton allow you to do what you wanted with the theme or is there still some work to be done?

Thanks,

- Lochemage

**Comment by dpage** [comment]
Yes, it's all good now. Thanks!

On Sun, Mar 8, 2015 at 5:38 AM, Jeff Houde <notifications@github.com> wrote:

> Dave,
>
> Just a follow up, did the skeleton allow you to do what you wanted with
> the theme or is there still some work to be done?
>
> Thanks,
>
>    - Lochemage
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/WebCabin/wcDocker/issues/27#issuecomment-77734351>.
>



-- 
Dave Page
Blog: http://pgsnake.blogspot.com
Twitter: @pgsnake

EnterpriseDB UK: http://www.enterprisedb.com
The Enterprise PostgreSQL Company

**Comment by Lochemage** [comment]
Excellent, good to hear.
