### ISSUE TITLE
Impossible to remove the last panel in the layout

### ISSUE THREAD

**Issue by alinoson** [WebCabin/wcDocker#30]
Hi,
I m using wcDocker to manage dynamically a docking layout by adding or removing panels. I need to be able to remove a panel even if it is the last one in the layout. How can achieve that?

Thanks for your help.

Alinoson.

**Comment by Lochemage** [comment]
Alinoson,

The short answer is, you can't. Removing the last panel causes a number of
issues so it was just easier to prevent it from being removed. I'll take
some time this weekend to revisit the problem, though; I have an idea that
may work, but I won't be able to promise anything.


- Lochemage

**Comment by Lochemage** [comment]
Alinoson,

Alright, I've come up with a solution that may work for you, I don't know
why I didn't think of this before.  You can now close all panels. To solve
the issue I was having, when you close the last panel, I create an empty
placeholder panel that takes its place until another panel replaces it.
Technically it still means you can never remove all the panels, but at
least to the user it feels like they did since the placeholder panel is
completely blank with no title bar or anything and goes away as soon as
another panel becomes docked.

Please try it out for yourself and let me know if I've missed anything!

- Lochemage

**Comment by alinoson** [comment]
Hi Lochemage,
Thank you very much, i tried and it s working perfectly!!!

Best regards.

Alinoson
