### ISSUE TITLE
Issues With wcSplitter in a Vertical Orientation

### ISSUE THREAD

**Issue by cganas** [WebCabin/wcDocker#34]
I am attempting to create a vertical splitter inside of my panel; however, it is not showing either the top or bottom layout.

```javascript

    myDocker.registerPanelType('Dynamic View', {
        onCreate: function(myPanel, options) {
            myPanel.initSize(800, 800);
            var layout = myPanel.layout();

            var container = $('<div style="position:absolute:top:0px;left:0px;right:0px;bottom:0px;"></div>');
            layout.addItem(container);

            var splitter = new wcSplitter(container, myPanel, wcDocker.ORIENTATION.VERTICAL);
            splitter.initLayouts();

            var top = splitter.top();
            var bottom = splitter.bottom();

            top.addItem($("<div id='vtimelinebox'></div>"));
            top.addItem($($("#dynamic-template").remove().text()), 1, 0);

            bottom.addItem($($("#hexeditor-template").remove().text()), 0, 0);
            dynamicDef.resolve();
        },
    });
```

If I instead define it is a horizontal splitter (` wcSplitter(container, myPanel, wcDocker.ORIENTATION.HORIZONTAL)`the layouts work as expected.

**Comment by Lochemage** [comment]
Christopher,

I've tried a variation of your code above, except I can't use your templating system and I don't know what your vtimelinebox does with css, etc.

First, there is a typo in your container, there should be a semicolon after 'absolute'.

The most often reason that items don't show up into the layout is due to them being a height of 0. In most browsers you can just set 'height:100%' on your 'vtimelinebox' item and it will work, but Firefox requires that you also set the size on the table item inside the layout as well.  For this, there is a handy method [stretch](http://docker.api.webcabin.org/wcLayout.html#~stretch) you can call from the result of addItem.

````
top.addItem($("<div id='vtimelinebox' style='height:100%;'></div>")).stretch('100%', '100%');
````

Of course, you don't have to use 100%, you can use a px value as well.

Please let me know if this solves your issue.

**Comment by cganas** [comment]
Thank you for the assistance Jeff. It would appear the typo in the style declaration originated from the first code snippet in the [widget tutorial](http://docker.api.webcabin.org/tutorial-3.0-widgets.html)! I apologize for not providing a completely isolated working example of the issue. The issue was resolved with the correction in style. :)

**Comment by Lochemage** [comment]
ah, thanks for letting me know!  I will update the tutorial just so it hopefully doesn't happen again!
