### ISSUE TITLE
three or more IFrame appear over each other

### ISSUE THREAD

**Issue by arpanmukherjee1** [WebCabin/wcDocker#39]
Adding 3 iframes and overlapping the bottom two with last one focus. the bottom two z-index are not correct and the frame borders are hidden

![image](https://cloud.githubusercontent.com/assets/10557028/8247281/2e90df3a-166b-11e5-90f2-36b590d201c6.png)

**Comment by Lochemage** [comment]
There isn't much I can do about this. IFrames can not be part of the panel they are in because panels constantly change their position in the dom tree when they are moved. When an IFrame is moved in the dom tree, its contents are visibly reloaded. To avoid this, the IFrame widget creates the actual iFrame in an outside location that is separate from the panel structure, which means they are actually on top of the panels rather than inside.  A little bit of z-index'ing can fix some of those problems, but not all, unfortunately.

**Comment by arpanmukherjee1** [comment]
Yes i understand, iframes will reload when moved. But z-index can be dynamically assigned to wcIframe (container of the actual iframe) and +1 to the related panel.
On focus change the array _floatingList and recalulate the z-indexes based on the position.
I think this should solve it. What do you propose ? 
Also what other problems do you see ? I did not get it.

**Comment by Lochemage** [comment]
@arpanmukherjee1 

I have implemented your change with some slight modification. Please re-open if you find a problem.
