### ISSUE TITLE
edge snap ?

### ISSUE THREAD

**Issue by mc007** [WebCabin/wcDocker#41]
Hi,
this is the best I ever saw; thank you! I was waiting since long for this.

I am trying to figure out a tweak for snapping a panel vertical with full height of the target panel which has 
already 2 sub panels but horizontal splitted. When dragging a third panel onto the left  or right side of the dual panel, it only allows to split the upper or lower panel horizontally but not the full panel; and when dragging onto the border it only allows to add a side tab. 

I hope that makes sense; do you some little guidance where to start implementing this? That's the only thing which is really missing, else: top!
thanks,
btw, I made a require-js/AMD compatible port, if you like, let me know!
g

**Comment by Lochemage** [comment]
mc007,

Happy to hear that docker is getting some recognition, I have worked hard so far to make it a useful tool!

Window edge docking is a feature that is currently not supported, but I have thought about it. Before now, I have held off because the infrastructure wouldn't easily allow it. However, a lot has changed in some of the more recent updates and I believe it can now be implemented.

I will put this on my list of tasks to do next, thank you for your feedback!

**Comment by mc007** [comment]
Hi,
thanks for the heads up; ah, so its called edge snapping then; I will updated the title.

**Comment by Lochemage** [comment]
I've just made an update that will allow you to dock a panel along the full edge of the window instead of nested with a smaller panel by dragging a panel to the very edge.  Let me know how this works for you or if you have any issues.

**Comment by mc007** [comment]
Excellent, works  as expected! Just the other snappers seem now harder to get. But I guess its a matter of tuning in Layout.js. Also thanks for cleaning up the unneeded commas!

offtopic: the only left issue for me is to get rid of the title-bar completely, its consuming too much space  I will an issue after for that soon. 

![layout_sample](https://cloud.githubusercontent.com/assets/1205100/8499143/b309255e-218f-11e5-8b82-c576894ae32d.png)

**Comment by mc007** [comment]
ah, found my mistake for; when the title of a 'fixed' panel (not collapsible) is null or '', its not accepting panels at all; never mind :-)
