### ISSUE TITLE
Collapsibles

### ISSUE THREAD

**Issue by mc007** [WebCabin/wcDocker#42]
Hi,
after toying long enough now, I noticed a few very disturbing/confusing issues:

1. By default, the 'collapse' button removes a panel from the tab-container and minimizes it on the left/right/bottom. That's fine so far as long this is intended except:

- its really annoying to get the layout back, because actually you want just collapse the entire tab-container. Think of a standard right panel, holding multiple property tabs; only in rare cases you grab a property panel out

- the other problem with a collapsed panel is: when opening it, it seems to be impossible to resize the content of other panels correctly (_actualSize is wrong of course). 

The only real quick solutions to 'minimize' entire containers  to the right,left or bottom I came along were:

- extend the Splitter class for an arrow button
- introduce another default panel button which minimizes the holding splitter region
- use multiple dockers within a custom splitter setup.

So I have just 2 short questions for you (then I stop bothering you :-)

1. What do you think about these 3 ideas to minimize a splitter region? I mean, is that possible at all at the moment?

2. How can I resize other panels upon a panel-collapse,expand event correctly. At the moment, a collapsible doesn't cause sizing events since its acting as overlay panel. 

Thank you, and sorry for the long text; I really try to make sense out of it for me; Its now 3 days digging and I still don't know wcDocker is a dead-end since the code is also difficult to grasp. 

g

**Comment by mc007** [comment]
just to correct, multiple dockers won't work still panels can't be moved among them as I see

**Comment by mc007** [comment]
ok, I figured it out. Easiest was to turn wcSplitter into a 'ToggleSplitter' (arrow buttons in the splitter and for the panel toolbar as well)

**Comment by Lochemage** [comment]
mc007,

I'm glad you found a solution for your problem, but I thought I should comment anyway:

The collapse button is only part of the individual panel, there is currently no button system for entire frames of multiple tabbed panels.  However, you can always drag-drop the tab bar to move entire groups of panels elsewhere. This includes dragging the group of panels to a collapsed side bar (as long as it is visible).

Also, it is a known issue that multiple docker instances do not interact with each-other, in fact, there are probably a lot of problems when you try to use multiple. I just haven't had any priority to look into it since I haven't found a suitable reason why you would need multiple docker instances anyway.

**Comment by mc007** [comment]
hi, thanks!
yup, i understand the docker problem, really no need. doing toggle 2 buttons along the splitter bar took just 10 lines of code btw. fully enough; case solved :-)
I will check the 'snap on edge' feature as next,
see you around!
g
