### ISSUE TITLE
panel with collapsible false doens't accept new panels? 

### ISSUE THREAD

**Issue by mc007** [WebCabin/wcDocker#43]
Hi,
I am trying to have some fixed layout (border-container with left/center/right/top/bottom). In order to make those standard containers fixed, I did set collapsible to false but since then, they don't accept panels to be dragged onto them. Is that on purpose? I mean its a little misleading flag then..

**Comment by Lochemage** [comment]
mc007,

Collapsible should not have the behavior you are describing, but moveable false will.  The reason is that docking a panel relative to another panel essentially moves both panels. If one panel is marked as non-moveable, then you should not be able to use it as a drop target because it can not be moved (or pushed over in this case).

**Comment by mc007** [comment]
thanks you!,
ash on my head :-)
