### ISSUE TITLE
preserve splitter positions on resize? 

### ISSUE THREAD

**Issue by mc007** [WebCabin/wcDocker#47]
Hi,
wcSplitter uses already normalized values (0-1) for positions; thats just perfect! I was wondering how to preserve this positions after a browser-window resize. I am not sure whether its just not implemented yet or its on purpose? 

However, I was wondering where to implement this; I guess it goes into wcSplitter (after resize event), right? 

Thank you again!
guenter

**Comment by Lochemage** [comment]
mc007,

If I understand you correctly, you want the splitter bars to scale along with the window resize?

Currently, splitter bars recalculate themselves so that they **appear** not to have moved in relation to their pixel positions. If the recalculation was not done, then resizing the window would also cause the splitters to scale in relation to their percentage within the window.

In wcDocker, a splitter is simply a bar with two sides, so to get the illusion of three panes (with three panels making up three columns), we are actually using two splitters with one nested inside the other like this:
______________________________
|                      | _________________ |
|                      | |                |               | |
|    Panel 1      | |  Panel 2  | Panel 3  | |
|                      | |________| _______| |
|___________|__________________|

Of course, the user doesn't see where the splitters are nested, so if they were to move the left splitter, it would cause panels 2 and 3 to stretch or shrink together. Contrary to that, if the user were to move the right splitter, **only** panels 2 and 3 would resize and panel 1 wouldn't be touched.

To solve this, splitters recalculate their position whenever resizing occurs on their parent based on their current pixel position. Now when moving the left splitter, only panels 1 and 2 will resize and panel 3 will remain the same size as you would expect in a normal three pane'd splitter.

**Comment by mc007** [comment]
yes,
ok, thank you again for the detailed answer; it makes perfectly sense and after all it looks I am looking from the wrong angle on my problem, in my apps have the usual layout: 

- left - panel (custom accordion=navigation) : min-w=300px
- center - panel (tabs) : w=remaining (it needs to have a placeholder panel which bothers me a lot too btw. Otherwise, I can't have a 'right' panel for properties)
- right - panel (properties) : min-w=400px (the trouble maker, it never keeps the initial width on resize)
- bottom - panel (shell, logs,...) : min-h=200px

Its just example layout but pretty much includes all the problems I have about re-sizing. Am I missing something in the props to archive this? I tried quit a few things to maintain the right panel to be always at the last set width by the user, or its start-width but I couldn't get there. I hope its clear that left & right panel should keep its initial size whilst resizing and only center should resize. Do you think its possible with probs only, or should I better go for customizing the resize methods?

**Comment by Lochemage** [comment]
mc007,

With wcDocker, the user can move panels and dock them anywhere in the window, so there should never be a situation where you expect a panel to be placed in a certain location. Your right side window could easily be shifted to be the left side window, etc.

Unfortunately, since the splitter bars are designed to **not** move during resizing, the right and bottom most panels **must** resize to fill in the extra space. The only way it won't is if the panel has reached it's max size limit and therefore is forced to pull the splitter bar with it.

However, if you need to size the panel on initialization right at the start, you could set a desired width and height during the `wcDocker.addPanel` call.
http://docker.api.webcabin.org/wcDocker.html#toc11
http://docker.api.webcabin.org/wcDocker.html#~PanelOptions

```
myDocker.addPanel('panel', wcDocker.DOCK.RIGHT, null, {x: '400px'});
```

**Comment by mc007** [comment]
yeah yeah, I got these basics
ok, happy hacking time then  :-)

feel free to close this, and thanks again for the awesome support!
g
