### ISSUE TITLE
my enhancements list

### ISSUE THREAD

**Issue by gbaumgart** [WebCabin/wcDocker#50]
hi,
this is my ultimate list :-)

- api toggle to hide show a panel's tab-bar entirely (needed in nested layouts, or protected areas)
- api and gui for minimizing/maximizing one part of a splitter
- accordion (tabs don't really do the job)
- being able to make collapsibles sticky, hide & show will resize then other panels, not just an overlay
- protected areas/panels (an 'accept mask') to avoid multiple wcdockers
- bind wcdocker instances to their container instead of body; well except the mouse handler can handle multiple instances(ideal)

that's it :-)

thanks. 
![docker_2](https://cloud.githubusercontent.com/assets/1205100/8768251/507813d6-2e79-11e5-85d4-87d9bc1904ef.png)

**Comment by Lochemage** [comment]
mc007,

I appreciate your suggestions and I will try to answer them the best I can:

* api toggle to hide show a panel's tab-bar entirely (needed in nested layouts, or protected areas)
  * If I understand you correctly, this feature already exists. If you set a panel's title to `false`, the title and tabs will no longer be displayed. However, keep in mind that this will severely limit the users ability to interact with the panel as the tabbing system is responsible for most of them. In most cases, if you are going to hide the title/tabs, you will probably also want to set the panel as non-moveable, non-closeable, and private.
```js
    wcDocker.registerPanelType('panel', {
      isPrivate: true,
      onCreate: function(myPanel) {
        myPanel.title(false);
        myPanel.moveable(false);
        myPanel.closeable(false);
      }
    });
```
* api and gui for minimizing/maximizing one part of a splitter
  * Fairly simple to implement the functionality, but I don't know the best way to design the interface for this feature. How will the user perform this action for one side or the other?
* accordion (tabs don't really do the job)
  * If you are suggesting the ability to dock panels and stack them as an accordion style widget instead of only tabbing them, then I am afraid this would require too much refactoring of the entire system and therefore present its own long list of potential problems. Something like this would just be too large of a task for me to handle right now, I don't know if I'll ever have time for it.
  * On the other hand, if you just want to have an accordion style widget somewhere inside one of your panels, this you can do yourself or with some third party libraries. I don't plan to implement UI features that aren't specifically necessary for wcDocker to work unless they are a feature that requires special built in support to work. For example, iFrames, I only implemented the wcIFrame class because using one the normal way within a panel doesn't work, special consideration must be implemented.
* being able to make collapsibles sticky, hide & show will resize then other panels, not just an overlay
  * The collabsible system is meant to just be an overlay slide out window that does not interact with the rest of the docking interface. If you want your panel to `show` by pushing all the panels over and locking it into place, you can do this just by re-docking the panel back into the main layout.
* protected areas/panels (an 'accept mask') to avoid multiple wcdockers
  * I agree that better handling can be performed when someone uses multiple wcDockers, but for the time being, I haven't had any arguments as to why anyone would need to use more than one. Originally when I built the system, I had the thought that it may be necessary, so I decided to make wcDocker an object that you can create rather than a constant global thing.
* bind wcdocker instances to their container instead of body; well except the mouse handler can handle multiple instances(ideal)
  * Again, this ties to the previous question, for the most part instances of wcDocker are contained within their container element. Event handlers are bound to the body, but should only do anything when interacting with an element that belongs to itself. I admin, this is not well tested though, as it just hasn't been a necessity.


As for your screenshot, I can see the accordion style frame, I am assuming your intent is that any panel could be docked into the accordion. Also I am guessing that the `HOME` panel is the one you don't want the title visible for.

**Comment by Lochemage** [comment]
mc007,

Also, if you feel that others can benefit from using your theme (assuming that screenshot is actually using wcDocker with your own custom theme), I encourage you to share it with us!

**Comment by mc007** [comment]
Hi,
thanks again for the insightful answers; i am a little too busy right now to get through all, but the theme is here: https://github.com/mc007/wcDocker/blob/master/Themes/white.css but I am not really sure its really complete since there are 2 other themes layered in top (classic jQuery themes).

**Comment by Lochemage** [comment]
@mc007 

It seems you are correct, the theme seems to be missing some styling when used on its own. In any case, one of my goals for the future is to design a theme building website that will make it much easier to design your own themes.

**Comment by Lochemage** [comment]
@mc007 

I have begun working on a somewhat basic theme builder tool that may help you with your theme. You can keep track of its status from its new branch `feat-33-theme-builder` and issue #33. For the moment, it looks like I can put it all into a single panel type right on the demo site, but we shall see how things progress.

**Comment by mc007** [comment]
hi, having a themes for wcDocker makes little sense for me, I'd prefer its using something standard, g-material/bootstrap or similar; anything which makes it easier to integrate somewhere else :-)

**Comment by Lochemage** [comment]
@mc007 

I would agree with that, but any *standard* theme is still going to have to be made somehow.

**Comment by mc007** [comment]
sure :-)

**Comment by mc007** [comment]
dont bother too much about, will take care about sometime:

- get Right/Left/Bottom/Top - Panel/Frame() 

- and a way to group panels, meaning if there is something can be grouped as a square, i need that collection of objects which belong to this square. The idea is also dimm that groups, so only the active panel has full opacity, See https://cloud.githubusercontent.com/assets/1205100/9693569/aa681312-5351-11e5-9866-83883cb1de0c.png. 

- an action to maximize a panel (aka "distraction free" mode), I know its a little tricky.
:-)
g

**Comment by Lochemage** [comment]
@gbaumgart 

Each `wcDocker` keeps track of all `wcFrame` objects inside of it, among other things, so moving a frame from one to the other would require an exchange which also means they would have to know about each other (probably through some global listing). It would be tricky, but I don't believe it's impossible, it was also the reason why I did not make `wcDocker` a singleton, just in case this would be implemented.

Grouping panels sounds like a nice idea, although, I'm not entirely sure how intuitive it would be for the end user. In any case, implementing a frame type class that behaves as a group of split panels rather than strictly a panel tabber might be very useful for floating panels especially. To be able to group multiple panels side by side as a floating window would be extremely useful I think.

Maximizing might actually be pretty easy, if you were to detach it into a floating panel you could just maximize its size. The tricky part is getting it so when the user un-maximizes it, it goes back to its original docked position like it never moved.
