### ISSUE TITLE
adjusting Drag'n drop thresholds? 

### ISSUE THREAD

**Issue by gbaumgart** [WebCabin/wcDocker#59]
Hi,
sometimes til often its re-arranging panels by a click only (on title bar or center pane). I have some heavy GUI operations linked to some of the docker events but all of them run with a little delay which improved the problem already. 

I was wondering there is some possibility to adjust the drag'n drop behavior or thresholds. And sorry, I cant really provide a sample for that.

**Comment by Lochemage** [comment]
@mc007 

Take a look at [options](http://docker.api.webcabin.org/wcDocker.html#~Options) edgeAnchorSize and panelAnchorSize and let me know if this will work for you.  The syntax to use it is as follows:

```
var myDocker = new wcDocker($container, {
  edgeAnchorSize: '50px',
  panelAnchorSize: '15%'
});
```

These will set the thresholds for drag-drop behavior for both edge docking and normal docking, you can set these values to a simple number (pixel value) or a string with either 'px' or '%' in it.

**Comment by mc007** [comment]
hi
thanks, as always great support!

i used different variations of sizes but still the same. I think it should be about the time you're accepting/recognizing a drag itself, eg: the delta time of mouse down - time of mouse move (or similar).  

So if I could relax the that time a little that would go in the right direction. Please consider that I do have my own Dnd handlers on the $center content element. These handlers do also quite heavy...

any idea? 
g

**Comment by bulentv** [comment]
@mc007 

Can you please try this patch if it works for you. On my tests, it works : https://github.com/bulentv/wcDocker/commit/2c4ebfaf75d093829385dd7067376b68a3660900

I tried to add a new config option to set a delay between the mouse down and drag start. Note that I'm not sure this is the correct way to do this for now so I didn't created an official pull request.

**Comment by Lochemage** [comment]
@bulentv 

Interesting, I'd be happy to merge this in after testing. Could you make it a pull request?

**Comment by Lochemage** [comment]
@mc007 

I've merged in @bulentv 's update to the master branch, please let me know if this solves your issue.

**Comment by mc007** [comment]
hi,
thank you both, I couldn't test it yet. I am little stuck with using wcDocker directly (my for is here now: https://gitlab.com/xamiro/xdocker | AMD compatible) and integrating PRs or updates. Major problems for me are the code formatting (spaces instead of intends, unneeded commas), globals (instanceOf) and also the use of constants (global too). If we could agree on some polishing/cleanup/standard that would really help me on the long, i also could contribute with lots of API improvements/optimizations then....no offense :-) just some pain :-)

However, looks I will need to update quite some stuff before this patch, I am back to you probably next Monday.

**Comment by Lochemage** [comment]
@mc007 

I was not aware that you had problems using wcDocker directly.  I think as long as the necessary changes don't cause problems for everyone else not using AMD, you are welcome to make pull requests. Also, if there are specific requirements like making sure I use spaces instead of tabs, or to avoid using extra comma's, I will put priority on keeping any new changes within those parameters.

**Comment by mc007** [comment]
ok then thanks for the heads up. Currently I am also little in the dark about modules & classes; I am actually trying to leave 'Dojo-1' for something smaller and more compact. Dojo it self is moving to Typescript  which seems to cover a lot of modern JS problems but also opens a whole new bunch of other problems(build-step as for CSS and no direct JSDoc support, and worst: no real debugging support except bloody source maps = fails in ff30/fbug). 

Right now I am still looking at the options: feel welcome too because I don't know better than Typescript either (hate it, some love it)....

sorry for opening the box of pandorra like this; ...bloody web-development, every time I finish a code base, I can start from scratch again :-)

**Comment by Lochemage** [comment]
@mc007 

Sounds like you have your work cut out for you! I'm sure we can get wcDocker compatible with your machine so you won't have to do any extra steps every time an update comes in.

**Comment by mc007** [comment]
Hi,
if you or your users would accept require-js as dependency (only for ES5 target in AMD - Mode), then I could re-organize my fork for a Typescript-ready/compatible library(I am not doing it as Typescript!). That means:

1. I supply you with a large PR after or before the 3.0.0 milestone( i prefer a 3.0.0 RC): 
- a complete Grunt file which does all: doc generation/dist build/watcher
- the typescript definition file to make wcDocker compatible in typescript-environments (optional)
- the base for automated test - units (using 'intern'), fired through grunt
- the single file build will contain then require.js it self whereby the build step is running the require.js build tool. however, its up to the developer to change this to something smaller, there are more minimalistic require.js versions. The goal however is that wcDocker can run without build-steps at all. And the loader should be optional. AMD becomes here just an environment but not an obligation.

2. folder-structure will change to common layouts, ie: /src /test/ /build|dist etc...

3. all the points I listed will be resolved (no globals anymore, constants & classes are provided as AMD dependency)

4. all instanceOf calls will be replace with an internal function, to enable true OOP. Its still unclear I am switching to "DCL" for wcDocker classes. 

ok then, let me know. All this could be ready in 2 weeks....Also, if you wanna go that path, open another issue. we're offtopic here :-)

**Comment by mc007** [comment]
well, never mind...

**Comment by Lochemage** [comment]
@mc007 

I'm sorry, I didn't mean to ignore you... I am just not familiar with some of the the requirements you've mentioned so I have not been able to give you a definitive answer. I think that the majority of those suggestions will need to be done by you since you understand what is needed, and made into a pull request for me to merge in.  As long as the changes don't introduce bugs or require major changes by everyone who uses it, I will probably be okay with pulling them in.

**Comment by Lochemage** [comment]
@mc007 

Also, I want to keep the project as lightweight as possible. I will only add another library dependency if it is absolutely necessary; If possible, I would rather embed a small code snippet that does only what I need, rather than import an entire wide-spectrum library only to use one feature.

**Comment by mc007** [comment]
sure, I understand. but hey, things like wcDocker comes usually into the game in rather large applications (IDEs) which of course have different needs...anyway, feel free to 'upgrade' sometime; i am around for this.

**Comment by mc007** [comment]
All the changes listed above will land here: https://gitlab.com/xamiro/xdocker/tree/xdocker-3.0.0-pre. 
I send you another message in 2 weeks or so when its done; proper OOP/AOP, test units, true modularization and kicking out globals seems absolute necessary to me. I also started to kick out the the theme classes for bootstrap/material support....

However, hopefully & possibly you change your mind but for now I am not planning any PR. So serve you self :-)

After all, its around 25KB JS more (non-gzipped). Possibly I can remove around 10%+ of redundant code via OOP(DCL) and maybe some CSS as well. In regard of backward compatibility; you can still export the library to the global namespace, ie: "wcDocker", and so forth.

**Comment by Lochemage** [comment]
Awesome, I don't mind major changes to the entire system as long as it requires very little or no change from anyone using it.  If all the namespaces etc. are internal then it doesn't matter if they were to change.

We'll have to do something about some of the widget classes (`wcIFrame` and `wcTabFrame`) if you intend to remove them from the global namespace. Not saying I won't do it, just that if it is done then I'd like it to be as easy as possible for someone who is unaware of these changes to quickly find out and repair it. For example, temporarily re-defined the global values so they still exist, but print out error messages explaining how to fix it.

As for unit tests, I'd love to add that architecture into the mix, I do so with my backend server side stuff. I just haven't had the time or priority to figure out a system for it yet.

25KB added to the build files are no big deal, I mainly just want to keep external dependencies down, as it increases my point of failure as well as requires all users to know about and include within their projects. I feel that I already use more than I want to. A necessary evil I think.

I look forward to what you come up with. If at all possible, though, please send me updates little by little instead of one giant update!

**Comment by mc007** [comment]
hell ya, sure. Keeping dependencies down is one my highest priority too. Unfortunately web-development wants things done different now,... Node.js/Grunt/Buildsteps, I hate it all...but hey, it connects us and code pretty well. I finally started forgetting the mess it creates :-). I toyed with  Typescript  & Webstorm 2 days: pretty awesome, code-completion and compiler warnings works out of the box, pretty handy for API newbies too btw.

then, 'removing' wcClass* from global  isn't really the goal, its rather about having real classes I can override/subclass. By default all base-classes go into global anyway (Grunt-task), no changes for you or your users. In my apps, i need quite different versions of wcDocker, panel, etc...

unit-tests: also just a developer dependency (Node.js "intern"). Seems to work pretty good.

ok then, I will keep you posted, its my first lib I will port to the "new world", so please be patient :-)

**Comment by Lochemage** [comment]
@mc007 

Ah, I understand. I'm fine with changing the class objects into actual class-type objects that support inheritance.

I'm less worried about dependencies due to unit testing, that would not effect the end user unless they actually want to run those tests themselves. I also have a lot of experience with Node, so have no problems with that.

**Comment by Lochemage** [comment]
@gbaumgart 

Closing this issue as it seems like it has now been resolved. Please reopen if I missed anything.
