### ISSUE TITLE
Ability to maximize panels

### ISSUE THREAD

**Issue by arpanmukherjee1** [WebCabin/wcDocker#76]
@Lochemage 
I am currently implementing feature for maximization of the panels.

I tried to make the panel floating modal and then redock to the same place on restore. But this destroys and reloads the panel contents. So this is not the correct way for me as the panels must not reload.

Second thing i tried was to set CSS of the frame to height width 100%. This approach works and contents take up entire docker space. But i cannot place a restore button. Also there are issues while resizing.

Can you suggest how to implement this feature fully?

**Comment by gbaumgart** [comment]
what you mean by maximize the panel, its content or indeed the entire panel ? I found resizing the content only is way easier, at least you don't have to 'restore' sizes & positions.

**Comment by Lochemage** [comment]
@arpanmukherjee1 

I agree with what @gbaumgart, it may be easier to continue with your second method where you do not really move the panel at all from it's current location, but just expand the layout so it fills the area. If you are trying to use a built in panel button as your restore button, this won't work since those buttons are outside of the layout (and on the frame that contains it). Since you are not moving the frame itself, you will need to come up with another way to show the restore button. You may be able to use the same button classes, however, as they are built to automatically float in the upper right.

**Comment by arpanmukherjee1** [comment]
@Lochemage  and @gbaumgart  you are correct. I am only expanding the contents of the panel and add a button to the body that floats to the upper right corner.
The button is removed when the panel is restored.

**Comment by Lochemage** [comment]
@arpanmukherjee1 

If you would like, perhaps you can submit a pull request to have this feature added to docker for everyone?

**Comment by arpanmukherjee1** [comment]
@Lochemage 
Ok. I will as soon as i can. Thanks.

**Comment by Lochemage** [comment]
@arpanmukherjee1 

Just wanted to touch base with you, is this something you still plan to pull into the project?

Thanks

**Comment by gbaumgart** [comment]
Hey, after a while I finally also implemented a sort of 'maximize' function on panels.  Its still little incomplete but works out well for me: https://gist.github.com/gbaumgart/d4bcf64a2402c4f5a013 . I use this for simple cases where i just want to to hide some panels entirely (ie: a property view). You could easily extend this for maximizing panels completely (multiple wcFrames)

ps: didn't test the code....
