### ISSUE TITLE
tab - bar text - rotation

### ISSUE THREAD

**Issue by gbaumgart** [WebCabin/wcDocker#82]
hi,
I know you are very busy and I don't want to bother you too much. I am trying to get a PR together which enables any Bootstrap (3-4) themes to be applied to wcDocker. The problem is that the entire tab bar is rotated and not just the text. After a few hours I gave up since there seem to be some calculations involved which are based on your CSS, making it rotated. 

![image](https://cloud.githubusercontent.com/assets/1205100/11077600/3d5ab5c4-8801-11e5-92b0-589027cee7c5.png)

If there is a slight chance that wcDocker doesn't rotate the tab-bar text, let me know. I would prepare you a version which has the theme as shown; otherwise close this here, I will try harder then :-)

thanks,g

**Comment by Lochemage** [comment]
@gbaumgart 

I apologize for not responding to this one, it was easier to rotate the entire bar since a lot of the same code could simply be re-used. I see two potential solutions in this case, the first would be to re-factor the tab system with a separate version for each location, and the second would be to add a wcDocker option that simply disables tab orientations.

**Comment by gbaumgart** [comment]
Thanks, I will look into it;
but hey, no worry; its bloody christmas time ;-)
